name: ESET Key Generator

on:
  workflow_dispatch:
    inputs:
      account:
        description: 'Number of Accounts to be generated (default = 0)'
        required: false
        default: '0'
      key:
        description: 'Number of Keys to be generated (default = 1)'
        required: false
        default: '1'
      mail:
        description: 'Choose the mail provider to generate license'
        required: true
        type: choice
        options:
        - 1secmail
        - guerrillamail
        - developermail
        - mailticking
        - fakemail
        - inboxes
        - incognitomail
        default: fakemail
      key_type:
        description: 'Modes of operation'
        required: true
        type: choice
        options:
        - --key
        - --small-business-key
        - --vpn-codes
        default: --vpn-codes
      os:
        description: 'Operating System of runner'
        required: true
        type: choice
        options:
        - macOS
        - Linux
        - Windows
        default: Linux
      branch:
        description: "Repository branch (don't touch it if you don't know what it is!!!)"
        required: false
        type: choice
        options:
        - main
        - test
        default: main
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate key
        if: github.event.inputs.os == 'Linux' || github.event_name == 'schedule'
        run: |
          ACCOUNT=${{ github.event.inputs.account || 1 }}  # Default to 1 if not provided
          KEY=${{ github.event.inputs.key || 1 }}         # Default to 1 if not provided
          MAIL=${{ github.event.inputs.mail }}
          KEY_TYPE=${{ github.event.inputs.key_type }}
          BRANCH=${{ github.event.inputs.branch }}

          git clone -b ${BRANCH} https://github.com/Diana-Cl/Key-Gen.git
          cd Key-Gen
          
          # Setup env
          sudo apt update
          sudo apt install -y python3-pip python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          # Get current date and time
          CURRENT_TIME=$(date -u +"%Y-%m-%d %H:%M UTC")
          CURRENT_HOUR=$(date -u +"%H")

          # Check if this is the first run after midnight (00:00 UTC)
          if [ "$CURRENT_HOUR" -ge 0 ] && [ "$CURRENT_HOUR" -lt 4 ]; then
            echo "First run after midnight, resetting Eset-Keys.md"
            rm -f ../Eset-Keys.md
          fi

          # Temporary file to store new content
          TEMP_FILE=$(mktemp)

          # Generate keys and accounts
          if [[ ${ACCOUNT} -ne 0 && ${KEY} -ne 0 ]]; then
            python3 main.py --auto-detect-browser --account --email-api ${MAIL} --skip-update-check --no-logo --disable-progress-bar --disable-logging --repeat ${ACCOUNT}
            python3 main.py --auto-detect-browser ${KEY_TYPE} --email-api ${MAIL} --skip-update-check --no-logo --disable-progress-bar --disable-logging --repeat ${KEY}
            echo "# Run" >> $TEMP_FILE
            echo "## Generated at: $CURRENT_TIME - valid until 12 hours" >> $TEMP_FILE
            echo "" >> $TEMP_FILE
            echo "### ESET VPN Codes:" >> $TEMP_FILE
            cat ./*KEYS.txt | nl -w2 -s". " >> $TEMP_FILE
            echo "" >> $TEMP_FILE
            echo "Account Email: $(head -n 1 ./*ACCOUNTS.txt | cut -d' ' -f1)" >> $TEMP_FILE
            echo "Account Password: $(head -n 1 ./*ACCOUNTS.txt | cut -d' ' -f2)" >> $TEMP_FILE
            echo "" >> $TEMP_FILE
            echo "Licence Name: ESET VPN" >> $TEMP_FILE
            echo "Licence Key: $(head -n 1 ./*KEYS.txt)" >> $TEMP_FILE
            echo "Licence Out Date: $(date -u -d "+12 hours" +"%Y-%m-%d %H:%M UTC")" >> $TEMP_FILE
            echo "" >> $TEMP_FILE
          elif [[ ${ACCOUNT} -ne 0 ]]; then
            python3 main.py --auto-detect-browser --account --email-api ${MAIL} --skip-update-check --no-logo --disable-progress-bar --disable-logging --repeat ${ACCOUNT}
            echo "# Run" >> $TEMP_FILE
            echo "## Generated at: $CURRENT_TIME" >> $TEMP_FILE
            echo "" >> $TEMP_FILE
            echo "Account Email: $(head -n 1 ./*ACCOUNTS.txt | cut -d' ' -f1)" >> $TEMP_FILE
            echo "Account Password: $(head -n 1 ./*ACCOUNTS.txt | cut -d' ' -f2)" >> $TEMP_FILE
            echo "" >> $TEMP_FILE
          elif [[ ${KEY} -ne 0 ]]; then
            python3 main.py --auto-detect-browser ${KEY_TYPE} --email-api ${MAIL} --skip-update-check --no-logo --disable-progress-bar --disable-logging --repeat ${KEY}
            echo "# Run" >> $TEMP_FILE
            echo "## Generated at: $CURRENT_TIME - valid until 12 hours" >> $TEMP_FILE
            echo "" >> $TEMP_FILE
            echo "### ESET VPN Codes:" >> $TEMP_FILE
            cat ./*KEYS.txt | nl -w2 -s". " >> $TEMP_FILE
            echo "" >> $TEMP_FILE
            echo "Licence Name: ESET VPN" >> $TEMP_FILE
            echo "Licence Key: $(head -n 1 ./*KEYS.txt)" >> $TEMP_FILE
            echo "Licence Out Date: $(date -u -d "+12 hours" +"%Y-%m-%d %H:%M UTC")" >> $TEMP_FILE
            echo "" >> $TEMP_FILE
          fi

          if [ -s ./*KEYS.txt ]; then
            echo "Licence Key: $(head -n 1 ./*KEYS.txt)" >> ../Eset-Keys.md
          else
            echo "Licence Key: No keys generated" >> ../Eset-Keys.md
          fi

          # Append previous content if exists
          if [ -f ../Eset-Keys.md ]; then
            cat ../Eset-Keys.md >> $TEMP_FILE
          fi

          # Move temp file to final location
          mv $TEMP_FILE ../Eset-Keys.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Eset-Keys.md
          git commit -m "Update Eset-Keys.md with new keys"
          git push
